# Generated by Django 5.2 on 2025-05-01 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='enrollment_id',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
